### ISSUE TITLE
JPAQuery save() can not execute SQL for the first time after act startup

### ISSUE THREAD

**Issue by leeaee** [actframework/act-jpa-common#14]
The save() method is called, but no eclipselink SQL was print and DB not insert also. This is only when act startup and the first time call save method, but it's OK for the second time call it.

```java
    @PostAction
    public Created create(@Valid Admin admin) {
        AAA.requirePermission(user, Permissions.PERM_ADMIN_CHANGE);
        admin = saveAdmin(admin);
        logger.debug("Create new admin with id -> {}", admin.id);
        return Created.withLocation(context.urlContext() + "/" + admin.id);
    }

    @Transactional
    private Admin saveAdmin(Admin admin) {
        entryptPassword(admin);
        return dao.save(admin);
    }
```

**Comment by greenlaw110** [comment]
Fixed by cb72b7a.

The culprit is `TimestampAuditor`, which is constructed by JPA (eclipselink or hibernate) will register itself as a singleton:

```java
    public TimestampAuditor() {
        buildLookups();
        final App app = Act.app();
        final TimestampAuditor me = this;
        // register singleton as the first TimestampAuditor could be initialized
        // by ORM lib e.g Hibernate
        app.jobManager().on(SysEventId.SINGLETON_PROVISIONED, new Runnable() {
            @Override
            public void run() {
                app.registerSingleton(me);
            }
        }, true);
    }
``` 

The above code choose to run the registration logic in the current thread where JPAContext has already been initialised, and when the job is closed it will close the JPA context, and hence the EntityManager. which happens before save commit, therefore the following commit process won't success as the EM has closed.
